require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'CalendarsExample' do
  config = use_native_modules!
  
  use_react_native!(:path => config["reactNativePath"])

  target 'CalendarsExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'CalendarsExample-tvOS' do
  # Pods for CalendarsExample-tvOS

  target 'CalendarsExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
