import { CalendarProps } from './calendar';
import { CalendarListProps } from './calendar-list';
import { AgendaProps } from './agenda';
import { ReservationListProps } from './agenda/reservation-list';
import { MarkingProps } from './calendar/day/marking';
export declare function shouldUpdate(props: any, newProps: any, paths: string[]): boolean;
export declare function extractComponentProps(component: any, props: any, ignoreProps?: string[]): any;
export declare function extractDotProps(props: MarkingProps): {
    theme: import("./types").Theme | undefined;
    color: string | undefined;
    marked: boolean | undefined;
    selected: boolean | undefined;
    disabled: boolean | undefined;
    inactive: boolean | undefined;
    today: boolean | undefined;
};
export declare function extractDayProps(props: CalendarProps): {
    state: import("./types").DayState | undefined;
    marking: MarkingProps | undefined;
    markingType: import("./types").MarkingTypes | undefined;
    theme: import("./types").Theme | undefined;
    onPress: ((date?: import("./types").DateData) => void) | undefined;
    onLongPress: ((date?: import("./types").DateData) => void) | undefined;
    date: string | undefined;
    disableAllTouchEventsForDisabledDays: boolean | undefined;
    disableAllTouchEventsForInactiveDays: boolean | undefined;
    dayComponent: import("react").ComponentType<import("./calendar/day").DayProps & {
        date?: import("./types").DateData;
    }> | undefined;
    testID: string | undefined;
};
export declare function extractHeaderProps(props: CalendarProps): {
    month: import("xdate") | undefined;
    addMonth: ((num: number) => void) | undefined;
    theme: import("./types").Theme | undefined;
    firstDay: number | undefined;
    displayLoadingIndicator: boolean | undefined;
    showWeekNumbers: boolean | undefined;
    monthFormat: string | undefined;
    hideDayNames: boolean | undefined;
    hideArrows: boolean | undefined;
    renderArrow: ((direction: import("./types").Direction) => import("react").ReactNode) | undefined;
    onPressArrowLeft: ((method: () => void, month?: XDate) => void) | undefined;
    onPressArrowRight: ((method: () => void, month?: XDate) => void) | undefined;
    disableArrowLeft: boolean | undefined;
    disableArrowRight: boolean | undefined;
    disabledDaysIndexes: number[] | undefined;
    renderHeader: ((date?: XDate) => import("react").ReactNode) | undefined;
    customHeaderTitle: JSX.Element | undefined;
    webAriaLevel: number | undefined;
    numberOfDays: number | undefined;
    current: string | undefined;
    timelineLeftInset: number | undefined;
    testID: string | undefined;
    onHeaderLayout: ((event: import("react-native").LayoutChangeEvent) => void) | undefined;
};
export declare function extractCalendarProps(props: CalendarListProps): {
    theme?: import("./types").Theme;
    style?: import("react-native").StyleProp<import("react-native").ViewStyle>;
    current?: string;
    initialDate?: string;
    minDate?: string;
    maxDate?: string;
    allowSelectionOutOfRange?: boolean;
    markedDates?: import("./types").MarkedDates;
    hideExtraDays?: boolean;
    showSixWeeks?: boolean;
    onDayPress?: (date: import("./types").DateData) => void;
    onDayLongPress?: (date: import("./types").DateData) => void;
    onMonthChange?: (date: import("./types").DateData) => void;
    onVisibleMonthsChange?: (months: import("./types").DateData[]) => void;
    disableMonthChange?: boolean;
    enableSwipeMonths?: boolean;
    headerStyle?: import("react-native").StyleProp<import("react-native").ViewStyle>;
    customHeader?: any;
    disabledByDefault?: boolean;
    disabledByWeekDays?: number[];
    testID?: string;
    month?: XDate;
    addMonth?: (num: number) => void;
    firstDay?: number;
    displayLoadingIndicator?: boolean;
    showWeekNumbers?: boolean;
    monthFormat?: string;
    hideDayNames?: boolean;
    hideArrows?: boolean;
    renderArrow?: (direction: import("./types").Direction) => import("react").ReactNode;
    onPressArrowLeft?: (method: () => void, month?: XDate) => void;
    onPressArrowRight?: (method: () => void, month?: XDate) => void;
    arrowsHitSlop?: import("react-native").Insets | number;
    disableArrowLeft?: boolean;
    disableArrowRight?: boolean;
    disabledDaysIndexes?: number[];
    renderHeader?: (date?: XDate) => import("react").ReactNode;
    customHeaderTitle?: JSX.Element;
    webAriaLevel?: number;
    accessibilityElementsHidden?: boolean;
    importantForAccessibility?: "auto" | "yes" | "no" | "no-hide-descendants";
    numberOfDays?: number;
    timelineLeftInset?: number;
    onHeaderLayout?: import("react-native").ViewProps["onLayout"];
    dayComponent?: React.ComponentType<import("./calendar/day").DayProps & {
        date?: import("./types").DateData;
    }>;
    state?: import("./types").DayState;
    marking?: MarkingProps;
    markingType?: import("./types").MarkingTypes;
    onPress?: (date?: import("./types").DateData) => void;
    onLongPress?: (date?: import("./types").DateData) => void;
    date?: string;
    disableAllTouchEventsForDisabledDays?: boolean;
    disableAllTouchEventsForInactiveDays?: boolean;
    accessibilityLabel?: string;
    children?: React.ReactNode | undefined;
    hitSlop?: import("react-native").Insets | undefined;
    id?: string | undefined;
    onLayout?: ((event: import("react-native").LayoutChangeEvent) => void) | undefined;
    pointerEvents?: "box-none" | "none" | "box-only" | "auto" | undefined;
    removeClippedSubviews?: boolean | undefined;
    nativeID?: string | undefined;
    collapsable?: boolean | undefined;
    needsOffscreenAlphaCompositing?: boolean | undefined;
    renderToHardwareTextureAndroid?: boolean | undefined;
    focusable?: boolean | undefined;
    shouldRasterizeIOS?: boolean | undefined;
    isTVSelectable?: boolean | undefined;
    hasTVPreferredFocus?: boolean | undefined;
    tvParallaxProperties?: import("react-native").TVParallaxProperties | undefined;
    tvParallaxShiftDistanceX?: number | undefined;
    tvParallaxShiftDistanceY?: number | undefined;
    tvParallaxTiltAngle?: number | undefined;
    tvParallaxMagnification?: number | undefined;
    onStartShouldSetResponder?: ((event: import("react-native").GestureResponderEvent) => boolean) | undefined;
    onMoveShouldSetResponder?: ((event: import("react-native").GestureResponderEvent) => boolean) | undefined;
    onResponderEnd?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onResponderGrant?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onResponderReject?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onResponderMove?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onResponderRelease?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onResponderStart?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onResponderTerminationRequest?: ((event: import("react-native").GestureResponderEvent) => boolean) | undefined;
    onResponderTerminate?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onStartShouldSetResponderCapture?: ((event: import("react-native").GestureResponderEvent) => boolean) | undefined;
    onMoveShouldSetResponderCapture?: ((event: import("react-native").GestureResponderEvent) => boolean) | undefined;
    onTouchStart?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onTouchMove?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onTouchEnd?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onTouchCancel?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onTouchEndCapture?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onPointerEnter?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerEnterCapture?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerLeave?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerLeaveCapture?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerMove?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerMoveCapture?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerCancel?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerCancelCapture?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerDown?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerDownCapture?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerUp?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerUpCapture?: ((event: import("react-native").PointerEvent) => void) | undefined;
    accessible?: boolean | undefined;
    accessibilityActions?: ReadonlyArray<import("react-native").AccessibilityActionInfo> | undefined;
    'aria-label'?: string | undefined;
    accessibilityRole?: import("react-native").AccessibilityRole | undefined;
    accessibilityState?: import("react-native").AccessibilityState | undefined;
    'aria-busy'?: boolean | undefined;
    'aria-checked'?: boolean | "mixed" | undefined;
    'aria-disabled'?: boolean | undefined;
    'aria-expanded'?: boolean | undefined;
    'aria-selected'?: boolean | undefined;
    'aria-labelledby'?: string | undefined;
    accessibilityHint?: string | undefined;
    accessibilityValue?: import("react-native").AccessibilityValue | undefined;
    'aria-valuemax'?: import("react-native").AccessibilityValue["max"] | undefined;
    'aria-valuemin'?: import("react-native").AccessibilityValue["min"] | undefined;
    'aria-valuenow'?: import("react-native").AccessibilityValue["now"] | undefined;
    'aria-valuetext'?: import("react-native").AccessibilityValue["text"] | undefined;
    onAccessibilityAction?: ((event: import("react-native").AccessibilityActionEvent) => void) | undefined;
    'aria-hidden'?: boolean | undefined;
    'aria-live'?: ("polite" | "assertive" | "off") | undefined;
    'aria-modal'?: boolean | undefined;
    role?: import("react-native").Role | undefined;
    accessibilityLiveRegion?: "none" | "polite" | "assertive" | undefined;
    accessibilityLabelledBy?: string | string[] | undefined;
    accessibilityViewIsModal?: boolean | undefined;
    onAccessibilityEscape?: (() => void) | undefined;
    onAccessibilityTap?: (() => void) | undefined;
    onMagicTap?: (() => void) | undefined;
    accessibilityIgnoresInvertColors?: boolean | undefined;
    accessibilityLanguage?: string | undefined;
    onScroll?: ((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) | undefined | undefined;
    columnWrapperStyle?: import("react-native").StyleProp<import("react-native").ViewStyle>;
    extraData?: any | undefined;
    getItemLayout?: ((data: ArrayLike<any> | null | undefined, index: number) => {
        length: number;
        offset: number;
        index: number;
    }) | undefined;
    initialNumToRender?: number | undefined | undefined;
    initialScrollIndex?: number | null | undefined | undefined;
    legacyImplementation?: boolean | undefined | undefined;
    numColumns?: number | undefined | undefined;
    onRefresh?: (() => void) | null | undefined | undefined;
    onViewableItemsChanged?: ((info: {
        viewableItems: Array<import("react-native").ViewToken>;
        changed: Array<import("react-native").ViewToken>;
    }) => void) | null | undefined | undefined;
    refreshing?: boolean | null | undefined | undefined;
    viewabilityConfig?: import("react-native").ViewabilityConfig | undefined;
    fadingEdgeLength?: number | undefined | undefined;
    ItemSeparatorComponent?: import("react").ComponentType<any> | null | undefined;
    ListEmptyComponent?: import("react").ComponentType<any> | import("react").ReactElement<any, string | import("react").JSXElementConstructor<any>> | null | undefined;
    ListFooterComponent?: import("react").ComponentType<any> | import("react").ReactElement<any, string | import("react").JSXElementConstructor<any>> | null | undefined;
    ListFooterComponentStyle?: import("react-native").StyleProp<import("react-native").ViewStyle>;
    ListHeaderComponent?: import("react").ComponentType<any> | import("react").ReactElement<any, string | import("react").JSXElementConstructor<any>> | null | undefined;
    ListHeaderComponentStyle?: import("react-native").StyleProp<import("react-native").ViewStyle>;
    debug?: boolean | undefined | undefined;
    disableVirtualization?: boolean | undefined | undefined;
    getItem?: ((data: any, index: number) => any) | undefined;
    getItemCount?: ((data: any) => number) | undefined | undefined;
    inverted?: boolean | null | undefined | undefined;
    maxToRenderPerBatch?: number | undefined | undefined;
    onScrollToIndexFailed?: ((info: {
        index: number;
        highestMeasuredFrameIndex: number;
        averageItemLength: number;
    }) => void) | undefined | undefined;
    onStartReached?: ((info: {
        distanceFromStart: number;
    }) => void) | null | undefined | undefined;
    onStartReachedThreshold?: number | null | undefined | undefined;
    progressViewOffset?: number | undefined | undefined;
    renderScrollComponent?: ((props: import("react-native").ScrollViewProps) => React.ReactElement<import("react-native").ScrollViewProps>) | undefined | undefined;
    updateCellsBatchingPeriod?: number | undefined | undefined;
    viewabilityConfigCallbackPairs?: import("react-native").ViewabilityConfigCallbackPairs | undefined;
    windowSize?: number | undefined | undefined;
    CellRendererComponent?: import("react").ComponentType<import("react-native").CellRendererProps<any>> | null | undefined;
    contentContainerStyle?: import("react-native").StyleProp<import("react-native").ViewStyle>;
    decelerationRate?: "fast" | "normal" | number | undefined | undefined;
    invertStickyHeaders?: boolean | undefined | undefined;
    keyboardDismissMode?: "none" | "interactive" | "on-drag" | undefined | undefined;
    onContentSizeChange?: ((w: number, h: number) => void) | undefined | undefined;
    onScrollBeginDrag?: ((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) | undefined | undefined;
    onScrollEndDrag?: ((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) | undefined | undefined;
    onMomentumScrollEnd?: ((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) | undefined | undefined;
    onMomentumScrollBegin?: ((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) | undefined | undefined;
    showsHorizontalScrollIndicator?: boolean | undefined | undefined;
    showsVerticalScrollIndicator?: boolean | undefined | undefined;
    stickyHeaderHiddenOnScroll?: boolean | undefined | undefined;
    refreshControl?: import("react").ReactElement<import("react-native").RefreshControlProps, string | import("react").JSXElementConstructor<any>> | undefined;
    snapToInterval?: number | undefined | undefined;
    snapToOffsets?: number[] | undefined | undefined;
    snapToStart?: boolean | undefined | undefined;
    snapToEnd?: boolean | undefined | undefined;
    stickyHeaderIndices?: number[] | undefined | undefined;
    disableIntervalMomentum?: boolean | undefined | undefined;
    disableScrollViewPanResponder?: boolean | undefined | undefined;
    StickyHeaderComponent?: import("react").ComponentType<any> | undefined;
    alwaysBounceHorizontal?: boolean | undefined | undefined;
    alwaysBounceVertical?: boolean | undefined | undefined;
    automaticallyAdjustContentInsets?: boolean | undefined | undefined;
    automaticallyAdjustKeyboardInsets?: boolean | undefined | undefined;
    automaticallyAdjustsScrollIndicatorInsets?: boolean | undefined | undefined;
    bounces?: boolean | undefined | undefined;
    bouncesZoom?: boolean | undefined | undefined;
    canCancelContentTouches?: boolean | undefined | undefined;
    centerContent?: boolean | undefined | undefined;
    contentInset?: import("react-native").Insets | undefined;
    contentOffset?: import("react-native").PointProp | undefined;
    contentInsetAdjustmentBehavior?: "automatic" | "scrollableAxes" | "never" | "always" | undefined | undefined;
    directionalLockEnabled?: boolean | undefined | undefined;
    indicatorStyle?: "default" | "black" | "white" | undefined | undefined;
    maintainVisibleContentPosition?: null | {
        autoscrollToTopThreshold?: number | null | undefined;
        minIndexForVisible: number;
    } | undefined | undefined;
    maximumZoomScale?: number | undefined | undefined;
    minimumZoomScale?: number | undefined | undefined;
    onScrollAnimationEnd?: (() => void) | undefined | undefined;
    pinchGestureEnabled?: boolean | undefined | undefined;
    scrollEventThrottle?: number | undefined | undefined;
    scrollIndicatorInsets?: import("react-native").Insets | undefined;
    scrollToOverflowEnabled?: boolean | undefined | undefined;
    snapToAlignment?: "start" | "center" | "end" | undefined | undefined;
    onScrollToTop?: ((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) | undefined | undefined;
    zoomScale?: number | undefined | undefined;
    endFillColor?: import("react-native").ColorValue | undefined;
    scrollPerfTag?: string | undefined | undefined;
    overScrollMode?: "auto" | "always" | "never" | undefined | undefined;
    persistentScrollbar?: boolean | undefined | undefined;
};
export declare function extractCalendarListProps(props: AgendaProps): {
    pastScrollRange?: number;
    futureScrollRange?: number;
    calendarWidth?: number;
    calendarHeight?: number;
    calendarStyle?: import("react-native").ViewStyle;
    staticHeader?: boolean;
    showScrollIndicator?: boolean;
    animateScroll?: boolean;
    theme?: import("./types").Theme;
    style?: import("react-native").StyleProp<import("react-native").ViewStyle>;
    current?: string;
    initialDate?: string;
    minDate?: string;
    maxDate?: string;
    allowSelectionOutOfRange?: boolean;
    markedDates?: import("./types").MarkedDates;
    hideExtraDays?: boolean;
    showSixWeeks?: boolean;
    onDayPress?: (date: import("./types").DateData) => void;
    onDayLongPress?: (date: import("./types").DateData) => void;
    onMonthChange?: (date: import("./types").DateData) => void;
    onVisibleMonthsChange?: (months: import("./types").DateData[]) => void;
    disableMonthChange?: boolean;
    enableSwipeMonths?: boolean;
    headerStyle?: import("react-native").StyleProp<import("react-native").ViewStyle>;
    customHeader?: any;
    disabledByDefault?: boolean;
    disabledByWeekDays?: number[];
    testID?: string;
    month?: XDate;
    addMonth?: (num: number) => void;
    firstDay?: number;
    displayLoadingIndicator?: boolean;
    showWeekNumbers?: boolean;
    monthFormat?: string;
    hideDayNames?: boolean;
    hideArrows?: boolean;
    renderArrow?: (direction: import("./types").Direction) => import("react").ReactNode;
    onPressArrowLeft?: (method: () => void, month?: XDate) => void;
    onPressArrowRight?: (method: () => void, month?: XDate) => void;
    arrowsHitSlop?: import("react-native").Insets | number;
    disableArrowLeft?: boolean;
    disableArrowRight?: boolean;
    disabledDaysIndexes?: number[];
    renderHeader?: (date?: XDate) => import("react").ReactNode;
    customHeaderTitle?: JSX.Element;
    webAriaLevel?: number;
    accessibilityElementsHidden?: boolean;
    importantForAccessibility?: "auto" | "yes" | "no" | "no-hide-descendants";
    numberOfDays?: number;
    timelineLeftInset?: number;
    onHeaderLayout?: import("react-native").ViewProps["onLayout"];
    dayComponent?: React.ComponentType<import("./calendar/day").DayProps & {
        date?: import("./types").DateData;
    }>;
    state?: import("./types").DayState;
    marking?: MarkingProps;
    markingType?: import("./types").MarkingTypes;
    onPress?: (date?: import("./types").DateData) => void;
    onLongPress?: (date?: import("./types").DateData) => void;
    disableAllTouchEventsForDisabledDays?: boolean;
    disableAllTouchEventsForInactiveDays?: boolean;
    accessibilityLabel?: string;
    children?: React.ReactNode | undefined;
    hitSlop?: import("react-native").Insets | undefined;
    id?: string | undefined;
    onLayout?: ((event: import("react-native").LayoutChangeEvent) => void) | undefined;
    pointerEvents?: "box-none" | "none" | "box-only" | "auto" | undefined;
    removeClippedSubviews?: boolean | undefined;
    nativeID?: string | undefined;
    collapsable?: boolean | undefined;
    needsOffscreenAlphaCompositing?: boolean | undefined;
    renderToHardwareTextureAndroid?: boolean | undefined;
    focusable?: boolean | undefined;
    shouldRasterizeIOS?: boolean | undefined;
    isTVSelectable?: boolean | undefined;
    hasTVPreferredFocus?: boolean | undefined;
    tvParallaxProperties?: import("react-native").TVParallaxProperties | undefined;
    tvParallaxShiftDistanceX?: number | undefined;
    tvParallaxShiftDistanceY?: number | undefined;
    tvParallaxTiltAngle?: number | undefined;
    tvParallaxMagnification?: number | undefined;
    onStartShouldSetResponder?: ((event: import("react-native").GestureResponderEvent) => boolean) | undefined;
    onMoveShouldSetResponder?: ((event: import("react-native").GestureResponderEvent) => boolean) | undefined;
    onResponderEnd?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onResponderGrant?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onResponderReject?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onResponderMove?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onResponderRelease?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onResponderStart?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onResponderTerminationRequest?: ((event: import("react-native").GestureResponderEvent) => boolean) | undefined;
    onResponderTerminate?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onStartShouldSetResponderCapture?: ((event: import("react-native").GestureResponderEvent) => boolean) | undefined;
    onMoveShouldSetResponderCapture?: ((event: import("react-native").GestureResponderEvent) => boolean) | undefined;
    onTouchStart?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onTouchMove?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onTouchEnd?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onTouchCancel?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onTouchEndCapture?: ((event: import("react-native").GestureResponderEvent) => void) | undefined;
    onPointerEnter?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerEnterCapture?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerLeave?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerLeaveCapture?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerMove?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerMoveCapture?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerCancel?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerCancelCapture?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerDown?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerDownCapture?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerUp?: ((event: import("react-native").PointerEvent) => void) | undefined;
    onPointerUpCapture?: ((event: import("react-native").PointerEvent) => void) | undefined;
    accessible?: boolean | undefined;
    accessibilityActions?: ReadonlyArray<import("react-native").AccessibilityActionInfo> | undefined;
    'aria-label'?: string | undefined;
    accessibilityRole?: import("react-native").AccessibilityRole | undefined;
    accessibilityState?: import("react-native").AccessibilityState | undefined;
    'aria-busy'?: boolean | undefined;
    'aria-checked'?: boolean | "mixed" | undefined;
    'aria-disabled'?: boolean | undefined;
    'aria-expanded'?: boolean | undefined;
    'aria-selected'?: boolean | undefined;
    'aria-labelledby'?: string | undefined;
    accessibilityHint?: string | undefined;
    accessibilityValue?: import("react-native").AccessibilityValue | undefined;
    'aria-valuemax'?: import("react-native").AccessibilityValue["max"] | undefined;
    'aria-valuemin'?: import("react-native").AccessibilityValue["min"] | undefined;
    'aria-valuenow'?: import("react-native").AccessibilityValue["now"] | undefined;
    'aria-valuetext'?: import("react-native").AccessibilityValue["text"] | undefined;
    onAccessibilityAction?: ((event: import("react-native").AccessibilityActionEvent) => void) | undefined;
    'aria-hidden'?: boolean | undefined;
    'aria-live'?: ("polite" | "assertive" | "off") | undefined;
    'aria-modal'?: boolean | undefined;
    role?: import("react-native").Role | undefined;
    accessibilityLiveRegion?: "none" | "polite" | "assertive" | undefined;
    accessibilityLabelledBy?: string | string[] | undefined;
    accessibilityViewIsModal?: boolean | undefined;
    onAccessibilityEscape?: (() => void) | undefined;
    onAccessibilityTap?: (() => void) | undefined;
    onMagicTap?: (() => void) | undefined;
    accessibilityIgnoresInvertColors?: boolean | undefined;
    accessibilityLanguage?: string | undefined;
    onScroll?: (((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) & ((yOffset: number) => void)) | undefined;
    horizontal?: boolean | null | undefined | undefined;
    columnWrapperStyle?: import("react-native").StyleProp<import("react-native").ViewStyle>;
    keyboardShouldPersistTaps?: boolean | "always" | "never" | "handled" | undefined | undefined;
    extraData?: any | undefined;
    getItemLayout?: ((data: ArrayLike<any> | null | undefined, index: number) => {
        length: number;
        offset: number;
        index: number;
    }) | undefined;
    initialNumToRender?: number | undefined | undefined;
    initialScrollIndex?: number | null | undefined | undefined;
    keyExtractor?: ((item: any, index: number) => string) | undefined;
    legacyImplementation?: boolean | undefined | undefined;
    numColumns?: number | undefined | undefined;
    onRefresh?: ((() => void) & (() => void)) | undefined;
    onViewableItemsChanged?: ((info: {
        viewableItems: Array<import("react-native").ViewToken>;
        changed: Array<import("react-native").ViewToken>;
    }) => void) | null | undefined | undefined;
    refreshing?: boolean;
    viewabilityConfig?: import("react-native").ViewabilityConfig | undefined;
    fadingEdgeLength?: number | undefined | undefined;
    ItemSeparatorComponent?: import("react").ComponentType<any> | null | undefined;
    ListEmptyComponent?: import("react").ComponentType<any> | import("react").ReactElement<any, string | import("react").JSXElementConstructor<any>> | null | undefined;
    ListFooterComponent?: import("react").ComponentType<any> | import("react").ReactElement<any, string | import("react").JSXElementConstructor<any>> | null | undefined;
    ListFooterComponentStyle?: import("react-native").StyleProp<import("react-native").ViewStyle>;
    ListHeaderComponent?: import("react").ComponentType<any> | import("react").ReactElement<any, string | import("react").JSXElementConstructor<any>> | null | undefined;
    ListHeaderComponentStyle?: import("react-native").StyleProp<import("react-native").ViewStyle>;
    debug?: boolean | undefined | undefined;
    disableVirtualization?: boolean | undefined | undefined;
    getItem?: ((data: any, index: number) => any) | undefined;
    getItemCount?: ((data: any) => number) | undefined | undefined;
    inverted?: boolean | null | undefined | undefined;
    maxToRenderPerBatch?: number | undefined | undefined;
    onEndReached?: ((info: {
        distanceFromEnd: number;
    }) => void) | null | undefined | undefined;
    onEndReachedThreshold?: number | null | undefined | undefined;
    onScrollToIndexFailed?: ((info: {
        index: number;
        highestMeasuredFrameIndex: number;
        averageItemLength: number;
    }) => void) | undefined | undefined;
    onStartReached?: ((info: {
        distanceFromStart: number;
    }) => void) | null | undefined | undefined;
    onStartReachedThreshold?: number | null | undefined | undefined;
    progressViewOffset?: number | undefined | undefined;
    renderScrollComponent?: ((props: import("react-native").ScrollViewProps) => React.ReactElement<import("react-native").ScrollViewProps>) | undefined | undefined;
    updateCellsBatchingPeriod?: number | undefined | undefined;
    viewabilityConfigCallbackPairs?: import("react-native").ViewabilityConfigCallbackPairs | undefined;
    windowSize?: number | undefined | undefined;
    CellRendererComponent?: import("react").ComponentType<import("react-native").CellRendererProps<any>> | null | undefined;
    contentContainerStyle?: import("react-native").StyleProp<import("react-native").ViewStyle>;
    decelerationRate?: "fast" | "normal" | number | undefined | undefined;
    invertStickyHeaders?: boolean | undefined | undefined;
    keyboardDismissMode?: "none" | "interactive" | "on-drag" | undefined | undefined;
    onContentSizeChange?: ((w: number, h: number) => void) | undefined | undefined;
    onScrollBeginDrag?: (((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) & ((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void)) | undefined;
    onScrollEndDrag?: (((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) & ((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void)) | undefined;
    onMomentumScrollEnd?: (((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) & ((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void)) | undefined;
    onMomentumScrollBegin?: (((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) & ((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void)) | undefined;
    pagingEnabled?: boolean | undefined | undefined;
    scrollEnabled?: boolean | undefined | undefined;
    showsHorizontalScrollIndicator?: boolean | undefined | undefined;
    showsVerticalScrollIndicator?: boolean | undefined | undefined;
    stickyHeaderHiddenOnScroll?: boolean | undefined | undefined;
    refreshControl?: (import("react").ReactElement<import("react-native").RefreshControlProps, string | import("react").JSXElementConstructor<any>> & JSX.Element) | undefined;
    snapToInterval?: number | undefined | undefined;
    snapToOffsets?: number[] | undefined | undefined;
    snapToStart?: boolean | undefined | undefined;
    snapToEnd?: boolean | undefined | undefined;
    stickyHeaderIndices?: number[] | undefined | undefined;
    disableIntervalMomentum?: boolean | undefined | undefined;
    disableScrollViewPanResponder?: boolean | undefined | undefined;
    StickyHeaderComponent?: import("react").ComponentType<any> | undefined;
    alwaysBounceHorizontal?: boolean | undefined | undefined;
    alwaysBounceVertical?: boolean | undefined | undefined;
    automaticallyAdjustContentInsets?: boolean | undefined | undefined;
    automaticallyAdjustKeyboardInsets?: boolean | undefined | undefined;
    automaticallyAdjustsScrollIndicatorInsets?: boolean | undefined | undefined;
    bounces?: boolean | undefined | undefined;
    bouncesZoom?: boolean | undefined | undefined;
    canCancelContentTouches?: boolean | undefined | undefined;
    centerContent?: boolean | undefined | undefined;
    contentInset?: import("react-native").Insets | undefined;
    contentOffset?: import("react-native").PointProp | undefined;
    contentInsetAdjustmentBehavior?: "automatic" | "scrollableAxes" | "never" | "always" | undefined | undefined;
    directionalLockEnabled?: boolean | undefined | undefined;
    indicatorStyle?: "default" | "black" | "white" | undefined | undefined;
    maintainVisibleContentPosition?: null | {
        autoscrollToTopThreshold?: number | null | undefined;
        minIndexForVisible: number;
    } | undefined | undefined;
    maximumZoomScale?: number | undefined | undefined;
    minimumZoomScale?: number | undefined | undefined;
    onScrollAnimationEnd?: (() => void) | undefined | undefined;
    pinchGestureEnabled?: boolean | undefined | undefined;
    scrollEventThrottle?: number | undefined | undefined;
    scrollIndicatorInsets?: import("react-native").Insets | undefined;
    scrollToOverflowEnabled?: boolean | undefined | undefined;
    scrollsToTop?: boolean | undefined | undefined;
    snapToAlignment?: "start" | "center" | "end" | undefined | undefined;
    onScrollToTop?: ((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) | undefined | undefined;
    zoomScale?: number | undefined | undefined;
    endFillColor?: import("react-native").ColorValue | undefined;
    scrollPerfTag?: string | undefined | undefined;
    overScrollMode?: "auto" | "always" | "never" | undefined | undefined;
    nestedScrollEnabled?: boolean | undefined | undefined;
    persistentScrollbar?: boolean | undefined | undefined;
    renderDay?: (date?: XDate, item?: import("./types").AgendaEntry) => JSX.Element;
    renderList?: (listProps: ReservationListProps) => JSX.Element;
};
export declare function extractReservationListProps(props: AgendaProps): {
    items: import("./types").AgendaSchedule | undefined;
    selectedDay: import("xdate") | undefined;
    topDay: import("xdate") | undefined;
    onDayChange: (((day: XDate) => void) & ((data: import("./types").DateData) => void)) | undefined;
    showOnlySelectedDayItems: boolean | undefined;
    renderEmptyData: (() => JSX.Element) | undefined;
    onScroll: (((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) & ((yOffset: number) => void)) | undefined;
    onScrollBeginDrag: (((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) & ((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void)) | undefined;
    onScrollEndDrag: (((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) & ((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void)) | undefined;
    onMomentumScrollBegin: (((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) & ((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void)) | undefined;
    onMomentumScrollEnd: (((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void) & ((event: import("react-native").NativeSyntheticEvent<import("react-native").NativeScrollEvent>) => void)) | undefined;
    refreshControl: (import("react").ReactElement<import("react-native").RefreshControlProps, string | import("react").JSXElementConstructor<any>> & JSX.Element) | undefined;
    refreshing: boolean | undefined;
    onRefresh: ((() => void) & (() => void)) | undefined;
    reservationsKeyExtractor: ((item: import("./types").DayAgenda, index: number) => string) | undefined;
    date: (string & import("xdate")) | undefined;
    item: import("./types").AgendaEntry | undefined;
    theme: import("./types").Theme | undefined;
    rowHasChanged: ((a: import("./types").AgendaEntry, b: import("./types").AgendaEntry) => boolean) | undefined;
    renderDay: ((date?: XDate, item?: import("./types").AgendaEntry) => JSX.Element) | undefined;
    renderItem: ((reservation: import("./types").AgendaEntry, isFirst: boolean) => React.Component | JSX.Element) | undefined;
    renderEmptyDate: ((date?: XDate) => React.Component | JSX.Element) | undefined;
};
export declare function extractReservationProps(props: ReservationListProps): {
    date: import("xdate") | undefined;
    item: import("./types").AgendaEntry | undefined;
    theme: import("./types").Theme | undefined;
    rowHasChanged: ((a: import("./types").AgendaEntry, b: import("./types").AgendaEntry) => boolean) | undefined;
    renderDay: ((date?: XDate, item?: import("./types").AgendaEntry) => JSX.Element) | undefined;
    renderItem: ((reservation: import("./types").AgendaEntry, isFirst: boolean) => React.Component | JSX.Element) | undefined;
    renderEmptyDate: ((date?: XDate) => React.Component | JSX.Element) | undefined;
};
