export declare const textDayFontFamily = "System";
export declare const textMonthFontFamily = "System";
export declare const textDayHeaderFontFamily = "System";
export declare const todayButtonFontFamily = "System";
export declare const textDayFontWeight = "300";
export declare const textMonthFontWeight = "300";
export declare const textDayHeaderFontWeight: undefined;
export declare const todayButtonFontWeight = "600";
export declare const textDayFontSize = 16;
export declare const textMonthFontSize = 16;
export declare const textDayHeaderFontSize = 13;
export declare const todayButtonFontSize = 14;
export declare const textDayStyle: undefined;
export declare const dotStyle: undefined;
export declare const arrowStyle: undefined;
export declare const calendarBackground = "white";
export declare const textSectionTitleColor = "#b6c1cd";
export declare const textSectionTitleDisabledColor = "#d9e1e8";
export declare const selectedDayBackgroundColor = "#00BBF2";
export declare const selectedDayTextColor = "white";
export declare const todayBackgroundColor: undefined;
export declare const todayTextColor = "#00BBF2";
export declare const dayTextColor = "#2d4150";
export declare const textDisabledColor = "#d9e1e8";
export declare const textInactiveColor = "#d9e1e8";
export declare const dotColor = "#00BBF2";
export declare const selectedDotColor = "white";
export declare const disabledDotColor = "#d9e1e8";
export declare const inactiveDotColor = "#d9e1e8";
export declare const todayDotColor = "#00BBF2";
export declare const arrowColor = "#00BBF2";
export declare const disabledArrowColor = "#d9e1e8";
export declare const monthTextColor = "#2d4150";
export declare const indicatorColor: undefined;
export declare const agendaDayTextColor = "#7a92a5";
export declare const agendaDayNumColor = "#7a92a5";
export declare const agendaTodayColor = "#00BBF2";
export declare const agendaKnobColor = "#f2F4f5";
export declare const expandableKnobColor = "#e8ecf0";
export declare const backgroundColor = "#f2F4f5";
export declare const reservationsBackgroundColor = "#f2F4f5";
export declare const todayButtonTextColor = "#00BBF2";
export declare const todayButtonPosition: undefined;
export declare const weekVerticalMargin = 7;
