export declare const foregroundColor = "white";
export declare const backgroundColor = "#f2F4f5";
export declare const separatorColor = "#f2F4f5";
export declare const processedColor = "#a7e0a3";
export declare const processingColor = "#ffce5c";
export declare const failedColor = "#f67e7e";
export declare const textSecondaryColor = "#7a92a5";
export declare const textDefaultColor = "#2d4150";
export declare const textColor = "#43515c";
export declare const textLinkColor = "#00BBF2";
export declare const textDayFontFamily = "System";
export declare const textMonthFontFamily = "System";
export declare const textDayHeaderFontFamily = "System";
export declare const todayButtonFontFamily = "System";
export declare const textDayFontWeight = "300";
export declare const textMonthFontWeight = "300";
export declare const textDayHeaderFontWeight: undefined;
export declare const todayButtonFontWeight = "600";
export declare const textDayFontSize = 16;
export declare const textMonthFontSize = 16;
export declare const textDayHeaderFontSize = 13;
export declare const todayButtonFontSize = 14;
export declare const textDayStyle: undefined;
export declare const dotStyle: undefined;
export declare const arrowStyle: undefined;
export declare const calendarBackground = "white";
export declare const textSectionTitleColor = "#b6c1cd";
export declare const textSectionTitleDisabledColor = "#d9e1e8";
export declare const selectedDayBackgroundColor = "#00BBF2";
export declare const selectedDayTextColor = "white";
export declare const todayBackgroundColor: undefined;
export declare const todayTextColor = "#00BBF2";
export declare const dayTextColor = "#2d4150";
export declare const textDisabledColor = "#d9e1e8";
export declare const textInactiveColor = "#d9e1e8";
export declare const dotColor = "#00BBF2";
export declare const selectedDotColor = "white";
export declare const disabledDotColor: undefined;
export declare const inactiveDotColor: undefined;
export declare const todayDotColor: undefined;
export declare const arrowColor = "#00BBF2";
export declare const disabledArrowColor = "#d9e1e8";
export declare const monthTextColor = "#2d4150";
export declare const indicatorColor: undefined;
export declare const agendaDayTextColor = "#7a92a5";
export declare const agendaDayNumColor = "#7a92a5";
export declare const agendaTodayColor = "#00BBF2";
export declare const agendaKnobColor = "#f2F4f5";
export declare const todayButtonTextColor = "#00BBF2";
export declare const todayButtonPosition: undefined;
