const PREFIX = 'native.calendar';

export const CHANGE_MONTH_LEFT_ARROW = `${PREFIX}.CHANGE_MONTH_LEFT_ARROW`;
export const CHANGE_MONTH_RIGHT_ARROW = `${PREFIX}.CHANGE_MONTH_RIGHT_ARROW`;
export const SELECT_DATE_SLOT = `${PREFIX}.SELECT_DATE_SLOT`;
export const CALENDAR_KNOB = `${PREFIX}.CALENDAR_KNOB`;
export const STATIC_HEADER = 'STATIC_HEADER';
export const AGENDA_CALENDAR_KNOB = `${PREFIX}.AGENDA_CALENDAR_KNOB`;
export const HEADER_MONTH_NAME = 'HEADER_MONTH_NAME';
export const RESERVATION_DATE = `${PREFIX}.RESERVATION_DATE`;
export const HEADER_DAY_NAMES = `${PREFIX}.DAY_NAMES`;
export const WEEK_NUMBER = `${PREFIX}.WEEK_NUMBER`;
export const HEADER_LOADING_INDICATOR = `${PREFIX}.HEADER_LOADING_INDICATOR`;
