const PREFIX = 'native.calendar';

module.exports = {
  CHANGE_MONTH_LEFT_ARROW: `${PREFIX}.CHANGE_MONTH_LEFT_ARROW`,
  CHANGE_MONTH_RIGHT_ARROW: `${PREFIX}.CHANGE_MONTH_RIGHT_ARROW`,
  TODAY_DATE: `${PREFIX}.TODAY_DATE`,
  DISABLED_DATE: `${PREFIX}.DISABLED_DATE`,
  SELECTABLE_DATE: `${PREFIX}.SELECTABLE_DATE`
};